"""row-level security policies

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-21

Every statement is generated by app.db.rls from the registries in app.db.base,
so a new tenant table gets an identically shaped policy by adding one list entry
rather than by hand-writing SQL here.

PINNED TABLE LIST: the generators read a registry that later revisions extend.
Left unpinned, this migration would try to ENABLE ROW LEVEL SECURITY on tables
that revision 0004 and 0006 have not created yet, and a from-scratch `alembic
upgrade head` would fail -- while an incrementally-migrated database kept
working, because it ran this step back when the registry was shorter. Every
generator-driven migration therefore names the tables that exist at its own
revision.
"""

from collections.abc import Sequence

from alembic import op
from app.db.rls import (
    CREATE_APP_SCHEMA,
    CREATE_AUTH_LOOKUP,
    CREATE_GUC_FUNCTIONS,
    DROP_AUTH_LOOKUP,
    DROP_GUC_FUNCTIONS,
    disable_rls,
    drop_policy,
    enable_rls,
    policy_for,
)

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The tables revision 0001 creates. Nothing more.
TABLES_AT_THIS_REVISION = [
    "organizations",
    "users",
    "candidates",
    "interviews",
    "invites",
]


def upgrade() -> None:
    op.execute(CREATE_APP_SCHEMA)
    for statement in CREATE_GUC_FUNCTIONS:
        op.execute(statement)
    for statement in CREATE_AUTH_LOOKUP:
        op.execute(statement)

    for table in TABLES_AT_THIS_REVISION:
        for statement in enable_rls(table):
            op.execute(statement)
        op.execute(drop_policy(table))
        op.execute(policy_for(table))


def downgrade() -> None:
    for table in TABLES_AT_THIS_REVISION:
        op.execute(drop_policy(table))
        for statement in disable_rls(table):
            op.execute(statement)

    for statement in DROP_AUTH_LOOKUP:
        op.execute(statement)
    for statement in DROP_GUC_FUNCTIONS:
        op.execute(statement)
