"""row-level security policies

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-21

Every statement is generated by app.db.rls from the registries in app.db.base,
so a new tenant table gets an identically shaped policy by adding one list entry
rather than by hand-writing SQL here.
"""

from collections.abc import Sequence

from alembic import op
from app.db.rls import downgrade_statements, upgrade_statements

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for statement in upgrade_statements():
        op.execute(statement)


def downgrade() -> None:
    for statement in downgrade_statements():
        op.execute(statement)
