"""QuestionPlan, PlannedQuestion, RubricCriterion.

NO SEPARATE ``Rubric`` TABLE. A plan has exactly one rubric, so a Rubric row
would carry an id, a plan_id and nothing else -- a join that buys no flexibility
and costs every read an extra hop. Criteria hang off the plan directly, and
"the rubric" is simply that plan's criteria.

The status flow is the whole point of this model:

    DRAFT ---- recruiter edits, regeneration allowed ----> APPROVED ----> FROZEN

FROZEN is set when the interview starts and is permanent. An interview must be
scorable against the exact questions and weights it was conducted under; if the
rubric could still move afterwards, a score would not mean anything. Every
mutating path checks this, and the database enforces the weight invariant that
the scorer depends on.

A candidate must never read any of this -- it is the answer key. Hence the
USER_ONLY registration in db/base.py.
"""

import enum
import uuid
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TenantMixin, TimestampMixin, uuid_pk

if TYPE_CHECKING:
    from app.models.interview import Interview

# Weights are stored as exact decimals, not floats: the scorer multiplies by
# them and a rubric that sums to 0.9999999999 is a support ticket. Four decimal
# places is finer than any recruiter will ever set by hand.
WEIGHT_PRECISION = 5
WEIGHT_SCALE = 4
WEIGHT_TOLERANCE = Decimal("0.0001")


class PlanStatus(enum.StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    FROZEN = "FROZEN"


class PlanGenerationStatus(enum.StrEnum):
    """Tracks the async generation itself, separately from review state.

    Kept apart from PlanStatus because they answer different questions: "has the
    model produced anything yet" and "has a human signed it off". Collapsing them
    would make a failed generation indistinguishable from an unreviewed draft.
    """

    PENDING = "PENDING"
    GENERATING = "GENERATING"
    READY = "READY"
    FAILED = "FAILED"


plan_status_enum = Enum(
    PlanStatus,
    name="plan_status",
    values_callable=lambda e: [m.value for m in e],
    create_type=False,  # the migration owns CREATE TYPE
)
plan_generation_status_enum = Enum(
    PlanGenerationStatus,
    name="plan_generation_status",
    values_callable=lambda e: [m.value for m in e],
    create_type=False,
)


class QuestionPlan(Base, TenantMixin, TimestampMixin):
    """The interview script and its scoring rubric, for one interview."""

    __tablename__ = "question_plans"
    __table_args__ = (
        # One live plan per interview. Regeneration replaces the plan's contents
        # rather than adding a second row, so there is never ambiguity about
        # which plan an interview is being conducted against.
        UniqueConstraint("interview_id", name="uq_question_plans_interview_id"),
        Index("ix_question_plans_org_id_status", "org_id", "status"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    interview_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("interviews.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # The exact description version this was generated from. Nullable and
    # SET NULL: a deleted job must not delete the plan an interview was run
    # against, but the provenance link is worth keeping while it exists.
    job_description_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("job_descriptions.id", ondelete="SET NULL")
    )
    resume_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("resumes.id", ondelete="SET NULL")
    )

    status: Mapped[PlanStatus] = mapped_column(
        plan_status_enum, nullable=False, server_default=text("'DRAFT'")
    )
    generation_status: Mapped[PlanGenerationStatus] = mapped_column(
        plan_generation_status_enum, nullable=False, server_default=text("'PENDING'")
    )
    # Bumped by every accepted edit. The client sends the version it read, and a
    # mismatch is a 409 -- two recruiters editing the same plan must not have one
    # silently overwrite the other.
    version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))
    # Which model produced it. A rubric generated by a model we have since
    # replaced is worth being able to identify.
    generated_by: Mapped[str | None] = mapped_column(String(120))
    # When a recruiter signed the plan off, if they ever did.
    #
    # A TIMESTAMP RATHER THAN RELYING ON ``status``, because ``freeze``
    # overwrites status with FROZEN the moment the interview starts -- so after
    # any real interview there was no record left of whether a human had
    # reviewed the questions. APPROVED was written by one line and read by
    # nothing, which made recruiter sign-off decorative.
    #
    # NULL means nobody reviewed it: the interview ran against a plan the model
    # wrote and no person checked. That is permitted -- see
    # interview/service.start for why a candidate already on the call is not
    # turned away over it -- but a recruiter reading the resulting score is
    # entitled to know, so it travels with the report.
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error: Mapped[str | None] = mapped_column(Text)

    interview: Mapped["Interview"] = relationship()
    questions: Mapped[list["PlannedQuestion"]] = relationship(
        back_populates="plan",
        cascade="all, delete-orphan",
        order_by="PlannedQuestion.ordinal",
    )
    criteria: Mapped[list["RubricCriterion"]] = relationship(
        back_populates="plan",
        cascade="all, delete-orphan",
        order_by="RubricCriterion.ordinal",
    )

    @property
    def is_editable(self) -> bool:
        return self.status is not PlanStatus.FROZEN

    def __repr__(self) -> str:
        return f"<QuestionPlan {self.id} {self.status} v{self.version}>"


class PlannedQuestion(Base, TenantMixin, TimestampMixin):
    """One question the interviewer intends to ask.

    ``follow_up_hints`` are prompts for the live model, not a script: the
    interview is a conversation and the model decides whether a follow-up is
    warranted. They exist so a candidate who answers thinly gets probed on the
    thing that actually matters rather than whatever the model improvises.
    """

    __tablename__ = "planned_questions"
    __table_args__ = (
        UniqueConstraint("plan_id", "ordinal", name="uq_planned_questions_plan_id_ordinal"),
        CheckConstraint("length(btrim(body)) > 0", name="body_not_blank"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    plan_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("question_plans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)
    # NOT named `text`: that would shadow sqlalchemy.text for the remainder of
    # this class body, and every server_default=text(...) below it would fail
    # with "'MappedColumn' object is not callable".
    body: Mapped[str] = mapped_column(Text, nullable=False)
    # Ties the question to the criterion it produces evidence for, by name.
    # A plain string rather than a foreign key: the LLM emits both in one pass
    # and a hard reference would make a single mismatched name fail the whole
    # generation. The scorer treats an unmatched competency as ungraded.
    competency: Mapped[str | None] = mapped_column(String(120))
    follow_up_hints: Mapped[list] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    # Roughly how long this question deserves. The live pipeline uses it to
    # pace a fixed-length interview rather than to cut a candidate off.
    time_budget_secs: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("180")
    )

    plan: Mapped["QuestionPlan"] = relationship(back_populates="questions")

    def __repr__(self) -> str:
        return f"<PlannedQuestion {self.plan_id}#{self.ordinal}>"


class RubricCriterion(Base, TenantMixin, TimestampMixin):
    """One scored dimension, with its weight and level descriptors.

    ``descriptors`` maps a score band to what it looks like ("1": "...",
    "5": "..."). The scorer sends them to the model verbatim, which is what
    makes a score defensible: the band was defined before the answer was heard.
    """

    __tablename__ = "rubric_criteria"
    __table_args__ = (
        UniqueConstraint("plan_id", "ordinal", name="uq_rubric_criteria_plan_id_ordinal"),
        UniqueConstraint("plan_id", "name", name="uq_rubric_criteria_plan_id_name"),
        CheckConstraint("weight > 0 AND weight <= 1", name="weight_in_range"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    plan_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("question_plans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    weight: Mapped[Decimal] = mapped_column(
        Numeric(WEIGHT_PRECISION, WEIGHT_SCALE), nullable=False
    )
    descriptors: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    plan: Mapped["QuestionPlan"] = relationship(back_populates="criteria")

    def __repr__(self) -> str:
        return f"<RubricCriterion {self.name} w={self.weight}>"
